### ISSUE TITLE
Denk aan je core functionaliteit

### ISSUE THREAD

**Issue by krijnhoetmer** [MokhtarAkle/performance-matters-optimized-website#14]
Denk aan de core functionaliteit. Wat kan ik doen op deze pagina? En lukt dat ook op het meest brakke apparaat of de meest brakke browser die er is? Hoe zorg je dat dat gaat werken? (Hint: Progressive Enhancement, sprint 9)

https://github.com/MokhtarAkle/performance-matters-optimized-website/blob/90c56af694884a4579e76d976abedd6466560c05/views/index.ejs#L83-L84

**Comment by MokhtarAkle** [comment]
https://github.com/MokhtarAkle/performance-matters-optimized-website/blob/90c56af694884a4579e76d976abedd6466560c05/public/javascripts/script.js#LL484C18-L484C18

Progressive enhancement toegepast op nieuw filter element door deze default te weergeven en met JS te verstoppen. Afhandeling van HTML gedeelte werkt dan maar uiteraard filter zelf niet.
